@startuml Component Trace


participant sensor as "DistanceSweepSensor"
participant MotorController as "MotorController:IObjectDetector"
participant system as "System"

sensor ->> MotorController : object_detected(ObjectDetectionMsg msg)
activate MotorController

alt msg.distance in danger_zone
    MotorController -> MotorController : panic()
    
    note right
    object is in danger 
    zone (system must be 
    halted totally)
    end note

    activate MotorController
    MotorController -> system : shutdown()
    activate system
    MotorController <-- system
    deactivate system
    deactivate MotorController
else msg.distance in alert_zone
    ' object is in alert zone (motors must be deactivated)
    MotorController -> MotorController : deactivate_motors()
    
    note right
    object is in alert 
    zone (motors must
    be deactivated).
    end note

    activate MotorController
    MotorController -> system : deactivate_motors()
    activate system
    ' the system must response withing 500ms, otherwise
    ' the total system will be shutdown
    loop wait for result
        alt time elapsed 500ms
        
            MotorController -> system : shutdown()
        
            note right
            If the system doesn't response
            within 500ms, the message will
            be escalated to a full shutdown of
            the system
            end note

            activate system
            MotorController <-- system
            deactivate system 
        end
    end
    system ---> MotorController
    deactivate system
    deactivate MotorController
end


@enduml