@startuml Component Design

' interfaces
interface IObjectDetector
interface IObjectDetectorSweep
interface IMotorController

' components
component MotorController
component DistanceSweepSensor

' Component MotorController
MotorController -left- IObjectDetector
MotorController -right- IMotorController

' Component DistanceSweepSensor
DistanceSweepSensor -up-( IObjectDetector
DistanceSweepSensor -right- IObjectDetectorSweep

@enduml
