@startuml Component Design

' interfaces
interface ITalk

' components
component TalkerNode <<ros node>>
component ListenerNode <<ros node>>

' Component Talker
TalkerNode -( ITalk

' Component Listener
ListenerNode -left- ITalk

@enduml